function mantle(){var Q='',yb='" for "gwt:onLoadErrorFn"',wb='" for "gwt:onPropertyErrorFn"',jb='"><\/script>',$='#',Gb='&',Fc='.cache.html',ab='/',mb='//',Zb='11807EBB10612B49B7F8E2431D51C70F',_b='2636B4158AEF60AE9E088545F1D039A8',bc='29C4F418EA13092FA1C9441F19BDCE66',cc='327F1EA439A3C87A2669460E4609F985',dc='46D8E7496DCE2408D643759FCC096554',fc='47CA78025A3AF394C63A9E37D5BCA4DE',gc='49510F3A0AAED3BBCA1CD96F571C649D',hc='4B51AF76CEA249FA373C72B7FA09F65A',ic='4D60A9A6CE74E76AF86214C20368D98D',jc='4DE2F0B3619547BE5458BBE491A8290D',kc='507E47CDE4FB77196C22F18594EB4412',lc='522770C2B9ED8E630F167A3306185C68',mc='576C61A73606565C782F10778AE8E263',nc='644369A989D85399F35663247941B22D',oc='892C30B551BC587658C622F629D3F900',pc='8A25E73369CCEBD5DE6593599BB99BD9',qc='96E695E968CE1571B8C0895BAF584512',rc='973E0F24612BD01B984794E9DB1F02B0',sc='9AA1DC63CD13EFAB19AEF6FC6D3C19C8',Ec=':',qb='::',Nc='<script defer="defer">mantle.onInjectionDone(\'mantle\')<\/script>',ib='<script id="',tb='=',_='?',tc='AB327121882AFF701D0BCB4F4B328025',uc='AD8B05AF4C736D27171EB3760B122BE6',vc='BAD17A055E6E4069E7BCA5546FB24DB4',wc='BCDEBE3BB07F5E6988D3C15A11F27B64',vb='Bad handler "',xc='C018ADE9CEB4772AACC30B93F2E8314D',yc='D76A178A97AF2D1776D06D4D3D612BA5',zc='DA041EF9317A7599BD2FA3D171DFB4D1',Mc='DOMContentLoaded',Ac='E1F9606DE04D82CD37F1E8FC6542FCC0',Bc='E407519E55986D241247C17013CBF4EC',Cc='E4DAF88EE6257AE04A88AF8A3B4EE61F',Dc='F262489EA7161CEDE2F84E4090DA322C',kb='SCRIPT',Jb='Unexpected exception in locale detection, using default: ',Ib='_',Hb='__gwt_Locale',hb='__gwt_marker_mantle',lb='base',db='baseUrl',U='begin',T='bootstrap',cb='clear.cache.gif',sb='content',$b='de',ac='default',Eb='en',Z='end',Yb='fr',Sb='gecko',Tb='gecko1_8',V='gwt.codesvr=',W='gwt.hosted=',X='gwt.hybrid',xb='gwt:onLoadErrorFn',ub='gwt:onPropertyErrorFn',rb='gwt:property',Lc='head',Wb='hosted.html?mantle',Kc='href',Rb='ie6',Qb='ie8',Pb='ie9',zb='iframe',bb='img',ec='ja',Ab="javascript:''",Hc='link',Vb='loadExternalRefs',Db='locale',Fb='locale=',R='mantle',fb='mantle.nocache.js',pb='mantle::',nb='meta',Cb='moduleRequested',Y='moduleStartup',Ob='msie',ob='name',Lb='opera',Bb='position:absolute;width:0;height:0;border:none',Ic='rel',Nb='safari',eb='script',Xb='selectingPermutation',S='startup',Jc='stylesheet',gb='undefined',Ub='unknown',Kb='user.agent',Mb='webkit',Gc='xul.css';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=Q,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:U});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(V)!=-1||(c.indexOf(W)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(X)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(R);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return I(a)}}mantle=null;c.gwtOnLoad(z,R,t,y);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Y,millis:(new Date).getTime(),type:Z})}}
function D(){function e(a){var b=a.lastIndexOf($);if(b==-1){b=a.length}var c=a.indexOf(_);if(c==-1){c=a.length}var d=a.lastIndexOf(ab,Math.min(c,b));return d>=0?a.substring(0,d+1):Q}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(bb);b.src=a+cb;a=e(b.src)}return a}
function g(){var a=G(db);if(a!=null){return a}return Q}
function h(){var a=n.getElementsByTagName(eb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(fb)!=-1){return e(a[b].src)}}return Q}
function i(){var a;if(typeof isBodyLoaded==gb||!isBodyLoaded()){var b=hb;var c;n.write(ib+b+jb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=kb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return Q}
function j(){var a=n.getElementsByTagName(lb);if(a.length>0){return a[a.length-1].href}return Q}
function k(){var a=n.location;return a.href==a.protocol+mb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==Q){l=h()}if(l==Q){l=i()}if(l==Q){l=j()}if(l==Q&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(nb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(ob),g;if(f){f=f.replace(pb,Q);if(f.indexOf(qb)>=0){continue}if(f==rb){g=e.getAttribute(sb);if(g){var h,i=g.indexOf(tb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=Q}u[f]=h}}else if(f==ub){g=e.getAttribute(sb);if(g){try{A=eval(g)}catch(a){alert(vb+g+wb)}}}else if(f==xb){g=e.getAttribute(sb);if(g){try{z=eval(g)}catch(a){alert(vb+g+yb)}}}}}}
function F(a,b){return b in v[a]}
function G(a){var b=u[a];return b==null?null:b}
function H(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function I(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var J;function K(){if(!J){J=true;var a=n.createElement(zb);a.src=Ab;a.id=R;a.style.cssText=Bb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Y,millis:(new Date).getTime(),type:Cb});a.contentWindow.location.replace(t+M)}}
w[Db]=function(){var b=null;var c=Eb;try{if(!b){var d=location.search;var e=d.indexOf(Fb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Gb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=G(Db)}if(!b){b=m[Hb]}if(b){c=b}while(b&&!F(Db,b)){var h=b.lastIndexOf(Ib);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Jb+a)}m[Hb]=c;return b||Eb};v[Db]={de:0,'default':1,en:2,fr:3,ja:4};w[Kb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Lb)!=-1}())return Lb;if(function(){return b.indexOf(Mb)!=-1}())return Nb;if(function(){return b.indexOf(Ob)!=-1&&n.documentMode>=9}())return Pb;if(function(){return b.indexOf(Ob)!=-1&&n.documentMode>=8}())return Qb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Rb;if(function(){return b.indexOf(Sb)!=-1}())return Tb;return Ub};v[Kb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};mantle.onScriptLoad=function(){if(J){r=true;C()}};mantle.onInjectionDone=function(){q=true;o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Vb,millis:(new Date).getTime(),type:Z});C()};E();D();var L;var M;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(R))){m.location.reload();return}M=Wb;L=Q}o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:Xb});if(!B()){try{H([Yb,Pb],Zb);H([$b,Lb],_b);H([ac,Pb],bc);H([$b,Pb],cc);H([ac,Rb],dc);H([ec,Rb],fc);H([Yb,Lb],gc);H([ec,Lb],hc);H([ac,Tb],ic);H([Yb,Qb],jc);H([Eb,Lb],kc);H([ec,Qb],lc);H([ac,Qb],mc);H([Eb,Rb],nc);H([ac,Nb],oc);H([ec,Nb],pc);H([Eb,Nb],qc);H([Yb,Nb],rc);H([Yb,Tb],sc);H([Eb,Pb],tc);H([$b,Qb],uc);H([Eb,Qb],vc);H([Yb,Rb],wc);H([ec,Pb],xc);H([Eb,Tb],yc);H([ec,Tb],zc);H([$b,Nb],Ac);H([$b,Tb],Bc);H([ac,Lb],Cc);H([$b,Rb],Dc);L=x[I(Db)][I(Kb)];var N=L.indexOf(Ec);if(N!=-1){y=Number(L.substring(N+1));L=L.substring(0,N)}M=L+Fc}catch(a){return}}var O;function P(){if(!s){s=true;if(!__gwt_stylesLoaded[Gc]){var a=n.createElement(Hc);__gwt_stylesLoaded[Gc]=a;a.setAttribute(Ic,Jc);a.setAttribute(Kc,t+Gc);n.getElementsByTagName(Lc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(Mc,P,false)}if(O){clearInterval(O)}}}
if(n.addEventListener){n.addEventListener(Mc,function(){K();P()},false)}var O=setInterval(function(){if(/loaded|complete/.test(n.readyState)){K();P()}},50);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:Z});o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Vb,millis:(new Date).getTime(),type:U});n.write(Nc)}
mantle();